server.port: 8081

logging:
  level: 
    com.jpmorgn.bank.verification: DEBUG
  
sources:
  - 
    name: source1
    url: https://source1.com/v1/api/account/validate
  - 
    name: source2
    url: https://source2.com/v2/api/account/validate
